const syllabus_ccna: string[] = [
    "Day 1 – Network Fundamentals",
    "Network Devices",
    "Protocols and Models",
    "IPv4 Addressing",
    "IPv6 Addressing",
    "Introduction to Cisco Packet Tracer",
    "Basic & Initial Configuration of Cisco devices",
    "Day 2 – Switching concept",
    "Switching Introduction",
    "VLAN",
    "Inter-VLAN routing",
    "STP concepts",
    "Etherchannel",
    "Day 3 – Routing concept",
    "Routing Introduction",
    "Static Routing",
    "Troubleshooting Static Routing",
    "Single area OSPF",
    "Troubleshooting single area OSPF",
    "Day 4 – Network Services",
    "FHRP Concept",
    "DHCP",
    "ACL",
    "NAT",
    "Day 5 – Security & Automation",
    "Security fundamentals",
    "AAA",
    "Port Security",
    "DHCP Snooping & Dynamic ARP Inspection",
    "Introduction to modern networks",
    "Introduction to network automation",
  ];
  
  const syllabus_ccnp_encor: string[] = [
    "Day 1 – Core Networking Concepts and Architecture",
    "Review of foundational networking concepts (brief for advanced learners)",
    "Understanding Cisco enterprise architecture models",
    "Layer 2 technologies: VLANs, trunks, EtherChannel",
    "Layer 3 concepts: Routing protocols (OSPF, EIGRP, BGP overview)",
    "Network virtualization: VRF, Layer 2 and Layer 3 VPNs",
    "Day 2 – Advanced Routing and High Availability",
    "Advanced OSPF configurations (areas, redistribution, authentication)",
    "EIGRP deep dive (metrics, summarization, authentication)",
    "BGP in enterprise environments (peering, route filtering, attributes)",
    "High availability (HSRP, VRRP, GLBP)",
    "WAN connectivity: MPLS, DMVPN, SD-WAN introduction",
    "Day 3 – Network Security and Automation",
    "Securing enterprise networks (AAA, device hardening, TrustSec)",
    "Introduction to network security with IPsec VPNs",
    "Secure network management: SNMP, syslog, and NetFlow",
    "Automation and programmability: Introduction to Python and APIs",
    "Cisco DNA Center and SD-Access basics",
    "Day 4 – Wireless and QoS",
    "Wireless architecture and components",
    "WLAN deployment and troubleshooting basics",
    "Quality of Service (QoS) fundamentals",
    "Traffic shaping, policing, and congestion management",
    "QoS in WANs",
    "Day 5 – Monitoring, Troubleshooting, and Final Review",
    "Network monitoring tools and techniques",
    "Troubleshooting Layer 2 and Layer 3 issues",
    "Addressing security and wireless problems",
    "Practice labs and case studies",
    "Final Q&A session and preparation tips for CCNP ENCOR exam",
  ];
  
  const syllabus_ccnp_enarsi: string[] = [
    "Day 1 – Routing Fundamentals and EIGRP/OSPF",
    "Implementing and optimizing EIGRP (IPv4/IPv6)",
    "Troubleshooting EIGRP",
    "Implementing and optimizing OSPF (IPv4/IPv6)",
    "Troubleshooting OSPF",
    "Configure EIGRP (Classic/Named Mode) for IPv4 and IPv6",
    "EIGRP Stub Routing, Summarization, Default Routing",
    "EIGRP Load Balancing and Authentication",
    "Troubleshoot EIGRP Issues",
    "Configure OSPFv3 for IPv4 and IPv6",
    "OSPF Stub Areas, Summarization, Authentication",
    "Troubleshoot OSPF",
    "Day 2 – BGP and Redistribution",
    "Implementing IBGP and MP-BGP",
    "Optimizing and troubleshooting BGP",
    "Configuring and troubleshooting route redistribution",
    "Configure IBGP/EBGP and BGP Path Selection",
    "Advanced BGP features (Route Reflectors, MP-BGP for IPv4/IPv6)",
    "Troubleshoot BGP Issues",
    "Implement and manipulate redistribution using route maps",
    "Troubleshoot redistribution",
    "Day 3 – Configuring and Troubleshooting Route Redistribution",
    "Implementing Path Control",
    "Implement and manipulate redistribution using route maps",
    "Troubleshoot redistribution issues",
    "Implement Policy-Based Routing (PBR)",
    "Day 4 – MPLS & VPN",
    "Exploring MPLS",
    "Introducing MPLS L3 VPN architecture and routing",
    "Configuring Virtual Routing and Forwarding (VRF)-Lite",
    "Implementing DMVPN",
    "Configure Routing with VRF-Lite",
    "Implement Cisco IOS DMVPN",
    "Day 5 – Infrastructure Security and Services",
    "Implementing IPv6 First Hop Security",
    "Securing Cisco routers",
    "Troubleshooting DHCP and ACLs",
    "Infrastructure security: Control Plane Policing, uRPF",
    "Troubleshooting network management protocols",
    "Troubleshoot DHCPv4 and DHCPv6 Issues",
    "Configure and verify ACLs, CoPP, and uRPF",
    "Troubleshoot network management protocols",
    "Each day is designed to cover both theory and practical labs, ensuring a balanced and focused approach for ENARSI preparation",
  ]

  const syllabus_ccnp_enwlsi: string[] = [
    "Day 1 – Wireless Fundamentals and Design",
"Overview of Cisco Wireless LAN Architecture",
"WLAN design considerations",
"Deploying Wireless Access Points and Controllers",
"Wireless Network Configuration and Troubleshooting",
"Wireless Site Survey",
"Configuring WLAN Security Policies (WPA3, 802.1X, etc.)",
"Design and implement wireless roaming",
"Configuring WLANs on Cisco Wireless Controllers",
"Performing Site Surveys and WLAN Placement",
"Configuring and verifying WPA3 and 802.1X Security",
"Testing wireless coverage and roaming",
"Day 2 – Advanced WLAN Services and Security",
"Implementing Advanced WLAN Services (QoS, Band Steering, Load Balancing)",
"WLAN Authentication and Security (802.1X, RADIUS, EAP)",
"Wireless Intrusion Prevention Systems (WIPS)",
"Security Best Practices in Wireless Networks",
"Configuring QoS for Wireless Networks",
"Implementing 802.1X Authentication",
"Configuring WIPS on Cisco Wireless Controllers",
"Securing WLANs and Monitoring for Vulnerabilities",
"Day 3 – WLAN Troubleshooting and Monitoring",
"Troubleshooting WLAN Connectivity and Performance Issues",
"Wireless Signal Issues and Interference Troubleshooting",
"Monitoring WLAN Performance (Cisco Prime, Wireless LAN Controller)",
"Diagnosing Common WLAN Problems",
"Troubleshooting WLAN Connectivity and Roaming Issues",
"Analyzing Wireless Signal Quality and Interference",
"Using Cisco Prime for WLAN Monitoring and Troubleshooting",
"Performing Troubleshooting with Cisco Wireless LAN Controllers",
"Day 4 – Advanced Wireless Concepts and Mobility",
"Implementing and Troubleshooting Advanced Mobility Features",
"Cisco CleanAir Technology",
"Optimizing Wireless Networks for High-Density Environments",
"Cisco Mobility Express and its Configuration",
"Implementing and troubleshooting FlexConnect",
"Configuring and Troubleshooting Cisco CleanAir",
"Optimizing Wireless Coverage in High-Density Areas",
"Configuring Mobility Express and FlexConnect",
"Day 5 – Wireless Network Management and Advanced Topics",
"Managing WLANs with Cisco DNA Center",
"Implementing Wireless Network Assurance",
"Advanced Troubleshooting with Wireshark and Cisco Tools",
"End-to-End Wireless Network Design and Best Practices",
"Using Cisco DNA Center for Wireless Network Management",
"Implementing Wireless Assurance Tools",
"Performing End-to-End Troubleshooting with Wireshark and Cisco Tools",
"Designing a Full Wireless Network Implementation",
  ];
  
  const syllabus_ccnp_spcor: string[] = [
    "Day 1 – Architecture",
"Core architectures (Metro Ethernet, MPLS, unified MPLS, SR, SRTE, SRv6)",
"Transport technologies (xDSL, DWDM, DOCSIS, TDM, and xPON)",
"Mobility (packet core, RAN xhaul transport for 5G vRAN and ORAN transport)",
"Routed optical network",
"Describe Cisco network software architecture",
"NFV infrastructure",
"VNF workloads",
"Containers",
"Application hosting",
"MPLS QOS models (Pipe, Short Pipe, and Uniform)",
"MPLS TE QoS (MAM, RDM, CBTS, PBTS, and DS-TE)",
"DiffServ and IntServ QoS models",
"Trust boundaries between enterprise and SP environments",
"IPv6 flow label",
"Control plane protection techniques (LPTS and CoPP)",
"BGP-TTL security and protocol authentication",
"BGP prefix suppression",
"LDP security (authentication and label allocation filtering)",
"BGP sec",
"BGP flowspec",
"Emanagement plane security",
"Implement data plane security",
"Day 2 – Networking",
"Implement IS-IS (IPv4 and IPv6)",
"Implement OSPF (v2 and v3)",
"Explain BGP path selection algorithm",
"Implement BGP (v4 and v6 for IBGP and EBGP)",
"Implement routing policy language and route maps (BGP, OSPF, IS-IS)",
"Troubleshoot routing protocols",
"Neighbor adjacency (IS-IS, OSPF, BGP)",
"Route advertisement (IS-IS, OSPF, BGP)",
"Explain IPv6 transition (NAT44, NAT64, CGNAT, MAP-T and DS Lite)",
"Implement high availability",
"Day 3 – MPLS & Segment Routing",
"Implement MPLS",
"LDP sync",
"LDP session protection",
"LDP neighbors",
"Unified MPLS",
"MPLS OAM",
"Explain traffic engineering",
"ISIS and OSPF extensions",
"RSVP functionality",
"FRR",
"Explain segment routing",
"Segment types",
"SR control plane (BGP, OSPF, IS-IS)",
"Segment routing traffic engineering",
"TI-LFa",
"PCE-PCC architectures",
"Flexible algorithm",
"Locator, micro-segment, encapsulation, interworking gateway",
"Day 4 - Services",
"Explain VPN services",
"EVPN",
"Inter-AS VPN",
"CSC",
"mVPN",
"Configure L2VPN and Carrier Ethernet",
"Ethernet services (E-Line, E-Tree, E-Access, E-LAN)",
"IEEE 802.1ad, IEEE 802.1ah, and ITU G.8032",
"Ethernet OAM",
"VLAN tag manipulation",
"Configure L3VPN",
"Intra-AS VPN",
"Shared services (extranet and Internet)",
"Implement multicast services",
"PIM (PIM-SM, PIM-SSM, and PIM-BIDIR)",
"IGMP v1/v2/v3 and MLD",
"Implement QoS services",
"Classification and marking",
"Congestion avoidance, traffic policing, and shaping",
"Day 5 – Automation and Assurance",
"Explain the programmable APIs used to include Cisco devices in network automation",
"Interpret an external script to configure a Cisco device using a REST API",
"Explain the role of Network Services Orchestration (NSO)",
"Explain the high-level principles and benefits of a data modeling language, such as YANG",
"Explain configuration management tools, such as Ansible and Terraform",
"Explain Secure ZTP",
"Configure dial-in/out, TCP, TLS and mTLS certificates using gRPC and gNMI",
"Configure and verify NetFlow/IPFIX",
"Configure and verify NETCONF and RESTCONF",
"Configure and verify SNMP (v2c/v3)",
  ];

  const syllabus_ccnp_spvi: string[] = [
    "Day 1 – VPN Architecture",  
    "Compare VPN architecture",  
    "Troubleshoot underlay",  
    "Explain Layer 2 service architecture",  
    "Explain the L3VPN control plane operation",  
    "Explain the L3VPN data plane operation",  
    "Underlay label",  
    "VRF forwarding instance",  
    "VPNv6",  
    "Day 2 – Layer 2 VPNs",  
    "Troubleshoot L2VPN Services",  
    "Explain EVPN concepts",  
    "Implement Ethernet Operations, Administration, and Maintenance (E-OAM)",  
    "Implementing EVPN",  
    "Day 3 – Layer 3 VPNs",  
    "Describe routing requirements",  
    "Troubleshoot Intra-AS L3VPNs",  
    "Implement multicast VPN",  
    "Implement extranet/shared services",  
    "Describe Inter-AS L3VPNs",  
    "Describe CSC concepts",  
    "Day 4 – IPv6 VPNs",  
    "Explain routing requirements",  
    "MP-BGP (6VPE, 6PE)",  
    "PE-CE routing protocol",  
    "Troubleshoot IPv6 VPN provider edge PE-PE PE-CE",
  ]

  const syllabus_ccie_sp: string[] = [
    "Day 1 – Core Routing",  
"Interior Gateway Protocol",  
"Border Gateway Protocol",  
"Multicast",  
"Multiprotocol Label Switching",  
"MPLS traffic engineering",  
"Segment routing",  

"Day 2 – Architecture and Services",  
"Mobile infrastructure architecture",  
"Optical architecture",  
"Large-scale MPLS architecture",  
"Carrier Ethernet",  
"L3VPN",  
"Internet service",  
"Multicast VPN",  
"Quality of service for core, distribution, and access",  

"Day 3 – Access Connectivity",  
"BNG connectivity",  
"Design cloud-native BNG",  
"Design control and user plan separation",  
"Layer 2 connectivity",  
"IEEE 802.1ad (Q-in-Q) and ITU G.8032",  
"Spanning Tree Access Gateway (MST-AG and PVST-AG)",  
"Design and operate MC-LAG",  

"Day 4 – High Availability and Fast Convergence",  
"High availability",  
"SSO/NSF, NSR, and GR",  
"Routing/fast convergence",  
"IGP convergence",  
"LDP convergence",  
"BGP Prefix Independent Convergence (BGP-PIC)",  
"BFD",  
"LFA-FRR (LFA, remote LFA, and TI-LFA)",  
"MPLS TE FRR",  

"Day 5 – Security & Automation",  
"Control plane protection techniques (LPTS and CoPP)",  
"Routing protocol and LDP authentication and security",  
"BGP prefix-based and attribute-based filtering",  
"BGP-RPKI (origin AS validation)",  
"Implement and troubleshoot device management (MPP, SSH, and VTY)",  
"Implement and troubleshoot logging and SNMP security",  
"Implement and troubleshoot AAA",  
"Infrastructure security",  
"ACL compression and object groups",  
"uRPF",  
"RTBH and router hardening",  
"BGP Flowspec",  
"TLS and mTLS certificates using gRPC and gNMI",  
"Design MACsec",  
"Network automation",  
"Design, deploy, and optimize NSO service packages (Yang models, template based, Python-based, fastmap, reactive fastmap, CLE NEDs, NETCONF NEDs, and NSO northbound integration using RESTCONF)",  

  ]

  const syllabus_ospf: string[] = [
    "Day 1 – OSPF Fundamentals",  

    "Day 1A - Introduction to Routing and OSPF",  
    "Basics of routing and dynamic routing protocols",  
    "Overview of OSPF (Open Shortest Path First)",  
    "Characteristics of OSPF: link-state protocol, metric cost, and area structure",  
    
    "Day 1B - OSPF Terminology and Components",  
    "Router ID, Neighbor, and Adjacency",  
    "Link State Advertisement (LSA)",  
    "Link State Database (LSDB)",  
    
    "Day 1C - Planning and Designing OSPF",  
    "Single-area vs Multi-area OSPF",  
    "Selection of Area 0 (Backbone Area)",  
    "Common OSPF topologies",  
    
    "Day 1D - Hands-On: Basic Single-Area OSPF Configuration",  
    "Setting up Router ID",  
    "Enabling OSPF on interfaces",  
    "Verifying neighbors and LSDB",  
    
    "Day 2 – OSPF Implementation and Optimization",  
    
    "Day 2A - Multi-Area OSPF",  
    "LSA Types and Functions",  
    "Overview of Advantages of Multi-Area OSPF",  
    "Design and management of areas",  
    "Roles of Area Border Router (ABR) & ASBR",  
    
    "Day 2B - LSA Types and Functions",  
    "Overview of LSA Types (1-5, 7)",  
    "LSA distribution between areas",  
    
    "Day 2C - OSPF Metrics and Cost",  
    "Configuring and adjusting OSPF Cost",  
    "Load balancing in OSPF",  
    
    "Day 2D - Advanced OSPF Features",  
    "Route summarization",  
    "Redistribution with other routing protocols",  
    "Stub, Totally Stubby, and NSSA areas",  
    
    "Day 2E - Hands-On: Configuring Multi-Area OSPF",  
    "Setting up ABR and inter-area communication",  
    "Simulating route summarization and redistribution",  
    
    "Day 3 – Troubleshooting and Advanced Use Cases",  
    
    "Day 3A - OSPF Troubleshooting",  
    "Common OSPF issues and resolutions",  
    "Tools for troubleshooting (ping, traceroute, and OSPF-specific commands)",  
    "Understanding and resolving LSDB inconsistencies",  
    
    "Day 3B - OSPF Security",  
    "Configuring OSPF authentication (plaintext and MD5)",  
    "Best practices for OSPF security",  
    
    "Day 3C - Advanced Topics in OSPF",  
    "Fast convergence techniques",  
    "OSPF over MPLS and VPNs",  
    "OSPF in dual-stack (IPv4 and IPv6)",  
    
    "Day 3D - Hands-On: OSPF Troubleshooting and Advanced Scenarios",  
    "Identifying and resolving OSPF neighbor issues",  
    "Simulating OSPF route flapping and convergence",  
    "Configuring OSPF authentication", 
  ]

  const syllabus_isis: string[] = [
    "Day 1 – IS-IS Fundamentals",  

"Day 1A - Introduction to Routing and IS-IS",  
"History and use cases of IS-IS",  
"Comparison with other routing protocols (e.g., OSPF)",  
"Overview of IS-IS protocol structure and PDU types",  

"Day 1B - IS-IS Architecture and Terminology",  
"Areas, Levels (Level 1 and Level 2)",  
"IS (Intermediate System) and ES (End System)",  
"LSP (Link-State PDU) and TLVs",  

"Day 1C - Configuring Basic IS-IS",  
"Enabling IS-IS on interfaces",  
"Assigning IS-IS levels and areas",  
"Verifying basic IS-IS operation",  

"Day 2 – Advanced IS-IS Concepts",  

"Day 2A - Multi-Area IS-IS Networks",  
"Hierarchical design with Level 1 and Level 2",  
"Area boundaries and inter-area routing",  

"Day 2B - IS-IS Metrics and Optimization",  
"IS-IS metric types and adjustment",  
"Equal-Cost Multi-Path (ECMP) with IS-IS",  

"Day 2C - IS-IS for IPv6",  
"Dual-stack IS-IS operation",  
"IPv6 support with IS-IS TLV",  

"Day 2D - Hands-On: Multi-Area and IPv6 IS-IS Configuration",  
"Configuring Level 1/Level 2 routers",  
"Enabling IS-IS for IPv6",  

"Day 3 – Troubleshooting and Advanced Features",  

"Day 3A - IS-IS Database and LSP Analysis",  
"Understanding and analyzing LSDB",  
"Interpreting LSP content and TLVs",  
"Route Summarization and Redistribution",  
"Configuring route summarization in IS-IS",  
"Redistributing routes between IS-IS and other protocols",  

"Day 3B - Advanced Features of IS-IS",  
"Multi-topology IS-IS",  
"Fast convergence techniques",  

"Day 3C - Troubleshooting IS-IS",  
"Identifying and resolving neighbor issues",  
"Debugging IS-IS adjacency and LSDB inconsistencies",  

  ]

  const syllabus_bgp: string[] = [
    "Day 1 – BGP Fundamentals",  

    "Day 1A - Introduction to BGP",  
    "Role of BGP in the internet and enterprise networks",  
    "Differences between iBGP and eBGP",  
    "Autonomous System (AS) concept",  
    
    "Day 1B - Establishing BGP Sessions",  
    "BGP neighbor states and session establishment",  
    "Configuring eBGP and iBGP sessions",  
    "Verifying BGP peering",  
    
    "Day 1C - BGP Path Attributes (PAs)",  
    "Well-known and optional attributes",  
    "Understanding AS_PATH, NEXT_HOP, LOCAL_PREF, and MED",  
    
    "Day 1D - Hands-On: Basic BGP Configuration",  
    "Configuring and verifying eBGP and iBGP neighbors",  
    "Observing BGP table entries",  
    
    "Day 2 – Policy and Optimization in BGP",  
    
    "Day 2A - BGP Route Filtering and Policies",  
    "Using prefix lists and route maps",  
    "Inbound and outbound route filtering",  
    "AS_PATH filtering and regular expressions",  
    
    "Day 2B - BGP Path Selection Process",  
    "Understanding the decision-making process",  
    "Configuring LOCAL_PREF, MED, and AS_PATH prepending",  
    
    "Day 2C - Advanced BGP Features",  
    "Route Reflectors and Confederations",  
    "BGP communities and their applications",  
    "Multipath BGP and load balancing",  
    
    "Day 2D - Hands-On: Implementing BGP Policies",  
    "Applying route maps for path control",  
    "Configuring route reflectors and communities",  
    
    "Day 3 – Advanced Topics and Troubleshooting",  
    
    "Day 3A - BGP Scalability and Optimization",  
    "BGP timers and keepalive settings",  
    "BGP convergence optimization",  
    
    "Day 3B - BGP in Multi-Homed Environments",  
    "Best practices for multi-homed networks",  
    "Using BGP for traffic engineering",  
    
    "Day 3C - BGP with IPv6 and VPNs",  
    "Configuring BGP for IPv6 (MP-BGP)",  
    "Introduction to BGP/MPLS VPNs",  
    
    "Day 3D - Troubleshooting BGP",  
    "Common BGP issues and resolutions",  
    "Analyzing BGP session problems and route inconsistencies",  
    "Tools and best practices for BGP troubleshooting",  
    
    "Day 3E - Hands-On: BGP Troubleshooting and Advanced Scenarios",  
    "Resolving neighbor issues and routing inconsistencies",  
    "Simulating BGP traffic engineering scenarios",  
    
  ]

  const syllabus_mpls: string[] = [
    "Day 1 – MPLS Core Concepts and Basics",  

    "Day 1A - Introduction to MPLS",  
    "MPLS overview, architecture, and benefits",  
    "Key components: LSRs, LERs, and FECs",  
    
    "Day 1B - MPLS Label Distribution and Forwarding",  
    "Label switching, MPLS label stack, and forwarding equivalence classes (FEC)",  
    "Label Distribution Protocol (LDP) basics",  
    
    "Day 1C - Configuring MPLS Basics",  
    "Enabling MPLS on network devices",  
    "Establishing LDP sessions and verifying MPLS forwarding",  
    
    "Day 1D - Hands-On Lab: Basic MPLS Configuration",  
    "Configuring MPLS and LDP on routers",  
    "Observing MPLS labels and troubleshooting basic issues",  
    
    "Day 2 – MPLS Applications and VPNs",  
    
    "Day 2A - MPLS Layer 3 VPNs",  
    "VRF (Virtual Routing and Forwarding) overview",  
    "PE and CE roles in MPLS VPNs",  
    "Route exchange using MP-BGP",  
    
    "Day 2B - Traffic Engineering (MPLS TE)",  
    "RSVP-TE (Resource Reservation Protocol - Traffic Engineering) basics",  
    "Configuring MPLS TE tunnels and path selection",  
    "Explicit and dynamic path configurations",  
    
    "Day 2C - Hands-On Lab: MPLS VPNs and Traffic Engineering",  
    "Setting up MPLS Layer 3 VPNs",  
    "Creating and verifying MPLS TE tunnels",  
    
    "Day 3 – Advanced MPLS Features",  
    
    "Day 3A - Advanced MPLS Applications",  
    "Layer 2 VPNs (VPWS and VPLS)",  
    "MPLS in IPv6 environments",  
    "MPLS Segment Routing basics",  
    
    "Day 3B - MPLS QoS (Quality of Service)",  
    "MPLS EXP bits and Class of Service (CoS) mapping",  
    "Implementing QoS policies in MPLS networks",  
    
    "Day 3C - MPLS Security",  
    "Protecting the MPLS control plane",  
    "Security best practices for MPLS VPNs",  
    
    "Day 3D - Hands-On Lab: Advanced MPLS Scenarios",  
    "Implementing Layer 2 VPNs",  
    "Configuring QoS and testing MPLS security measures",  
    
    "Day 4 – Troubleshooting and Optimization",  
    
    "Day 4A - MPLS Troubleshooting Techniques",  
    "Identifying and resolving LDP and BGP-related issues",  
    "Debugging MPLS forwarding and label distribution problems",  
    
    "Day 4B - Optimization of MPLS Networks",  
    "Improving convergence time",  
    "Best practices for scalability and performance optimization",  
    
    "Day 4C - Case Studies and Real-World Scenarios",  
    "Multi-vendor MPLS configurations",  
    "Traffic engineering for specific applications",  
    
    "Day 4D - Hands-On Lab: Troubleshooting and Optimizing MPLS Networks",  
    "Simulating network failures and rerouting traffic",  
    "Resolving real-world MPLS configuration issues",  
    
  ]

  const syllabus_srmpls: string[] = [
    "Day 1 – Introduction to Segment Routing and MPLS",  

"Day 1A - Overview of Segment Routing",  
"Benefits of Segment Routing",  
"Key concepts: Segments, SR-TE (Traffic Engineering), and Path Computation",  
"Comparing SR with traditional MPLS signaling protocols (RSVP-TE, LDP)",  

"Day 1B - MPLS Overview and SR Integration",  
"MPLS label stack in SR",  
"SR-MPLS and the role of IGPs (OSPF, IS-IS)",  

"Day 1C - Segment Routing Global Block (SRGB) and Local Block (SRLB)",  
"Basic Configuration of Segment Routing",  
"Configuring SR on IGPs (OSPF, IS-IS)",  
"Assigning Node-SIDs and Adjacency-SIDs",  
"Verifying Segment Routing operation in MPLS",  

"Day 2 – Advanced Segment Routing Concepts",  

"Day 2A - Traffic Engineering with Segment Routing (SR-TE)",  
"Creating SR-TE tunnels and policies",  
"Path Computation Element (PCE) and its role",  
"Explicit and dynamic SR-TE paths",  

"Day 2B - SR Fast Reroute (TI-LFA)",  
"Configuring and enabling Fast Reroute for high availability",  
"Protection against link/node failures with TI-LFA",  

"Day 2C - Advanced SR Features",  
"Using Anycast-SID for load balancing and redundancy",  
"Role of Segment Routing in Multi-Topological networks",  

"Day 2D - Configuring SR-TE and TI-LFA",  
"Implementing SR-TE policies and validating traffic flows",  
"Setting up and testing Fast Reroute functionality",  

"Day 3 – SRv6 and Inter-domain SR",  

"Day 3A - Segment Routing over IPv6 (SRv6)",  
"Introduction to SRv6 and differences from SR-MPLS",  
"Benefits of SRv6 in modern networks",  
"Configuring SRv6 and integrating with MPLS",  

"Day 3B - SR Inter-Domain (Inter-AS) Configuration",  
"SR in multi-domain or multi-AS environments",  
"Creating Inter-AS SR policies",  
"Inter-AS traffic engineering and path computation",  

"Day 3C - Implementing SRv6",  
"Configuring and testing SRv6 in a lab environment",  
"Inter-domain routing with SR and MPLS",  

"Day 4 – Segment Routing in Large Networks",  

"Day 4A - SR Scaling and Optimization",  
"Managing large-scale SR-MPLS deployments",  
"Optimizing path selection and traffic engineering",  
"Advanced BGP integration with SR",  

"Day 4B - SR in Large-Scale Service Provider Networks",  
"Best practices for deploying SR in large provider environments",  
"Case studies on traffic engineering and network optimization",  

"Day 4C - SR with MPLS VPNs",  
"Integrating Segment Routing with MPLS VPNs for end-to-end traffic engineering",  
"Using SR to optimize MPLS VPN routing",  

"Day 4D - Scaling SR in Large Networks",  
"Configuring SR in large-scale topologies",  
"Verifying large-scale MPLS traffic flows",  

"Day 5 – Troubleshooting and Advanced Use Cases",  

"Day 5A - SR and MPLS Troubleshooting",  
"Identifying and resolving SR label allocation issues",  
"Debugging Segment Routing and MPLS issues",  
"Common SR failures and resolutions",  

"Day 5B - Advanced SR Use Cases",  
"SR in IoT, 5G, and cloud environments",  
"Optimizing multi-tenancy and SD-WAN with SR",  

"Day 5C - Troubleshooting Segment Routing",  
"Simulating SR-related issues and resolving them",  
"Validating network performance and rerouting scenarios",  

  ]

  const syllabus_srv6: string[] = [
    "Day 1 – SRv6 Fundamentals",  
    
    "Day 1A - Introduction to Segment Routing (SR)",  
    "SR overview, concepts, and benefits",  
    "Differences between traditional MPLS and Segment Routing",  
    "SRv6 and its advantages over SR-MPLS",  
    
    "Day 1B - SRv6 Basic Architecture",  
    "SRv6 Segment Routing Header (SRH) structure",  
    "SRv6 SID (Segment Identifier) types and functions",  
    "End-to-End SRv6 forwarding",  
    
    "Day 1C - Configuring SRv6 on Routers",  
    "Enabling SRv6 on IPv6 interfaces",  
    "Configuring SRv6 global and local SIDs",  
    "Basic SRv6 routing configuration",  
    
    "Day 2 – SRv6 Traffic Engineering and Path Selection",  
    
    "Day 2A - Traffic Engineering with SRv6",  
    "SRv6 vs traditional traffic engineering",  
    "Configuring SRv6 policies and path computation",  
    "Benefits of SRv6 for traffic optimization",  
    
    "Day 2B - SRv6 Path Computation",  
    "Controlling traffic paths with SRv6 policies",  
    "Configuring SRv6 explicit path and segment lists",  
    "Integrating SRv6 with SDN (Software-Defined Networking)",  
    "Hands-On: Configuring traffic engineering with SRv6",  
    
    "Day 3 – Advanced SRv6 Features and Use Cases",  
    
    "Day 3A - SRv6 Service Chaining",  
    "Concept of service chaining in SRv6",  
    "Configuration of SRv6 service chaining for network services",  
    "Use cases in security, load balancing, and application delivery",  
    
    "Day 3B - Network Slicing with SRv6",  
    "Introduction to network slicing",  
    "SRv6 and its role in enabling network slicing",  
    "Configuring SRv6 for virtual network management",  
    
    "Day 3C - SRv6 and MPLS Integration",  
    "Integrating SRv6 with MPLS networks",  
    "Benefits of SRv6-MPLS hybrid networks",  
    "Configuring SRv6 over MPLS",  
    
    "Day 4 – SRv6 Security and Automation",  
    
    "Day 4A - SRv6 Security Considerations",  
    "Security challenges in SRv6 networks",  
    "Configuring security features for SRv6",  
    "Protecting SRv6 paths and segments from attacks",  
    
    "Day 4B - Automation and Orchestration with SRv6",  
    "Automating SRv6 configuration and operations using SDN",  
    "Orchestrating SRv6 with network management tools",  
    "Use of REST APIs and other automation tools",  
    
    "Day 5 – Troubleshooting",  
    
    "Day 5A - SRv6 Troubleshooting",  
    "Common SRv6 issues and how to diagnose them",  
    "Tools for troubleshooting SRv6 (e.g., traceroute, ping, debug)",  
    "Understanding and resolving SRv6 path issues",  
    
    "Day 5B - SRv6 in Real-World Deployments",  
    "Use cases in service provider networks, data centers, and enterprise environments",  
    "Integration with existing networks and legacy systems",  
    "SRv6 deployment strategies and best practices",  
  ]

  const syllabus_vxlan: string[] = [
    "Day 1 – Introduction to VXLAN and Basic Configuration",  

    "Day 1A - Overview of VXLAN and its benefits",  
    "Network virtualization concepts",  
    "VXLAN compared to traditional VLAN",  
    
    "Day 1B - VXLAN Components and Architecture",  
    "VXLAN tunnel endpoints (VTEPs)",  
    "VXLAN encapsulation and header structure",  
    "VXLAN Network Identifier (VNI)",  
    
    "Day 1C - Basic VXLAN Configuration",  
    "Configuring VXLAN on physical and virtual devices",  
    "Setting up VTEPs and tunnels",  
    "Verifying VXLAN operations",  
    
    "Day 2 – Advanced VXLAN Configuration and Control Plane",  
    
    "Day 2A - VXLAN Overlay and Underlay Networks",  
    "VXLAN overlay network concepts",  
    "VXLAN underlay network requirements",  
    "IP routing and multicast setup for VXLAN",  
    
    "Day 2B - Integrating VXLAN with SDN",  
    "VXLAN and its role in SDN environments",  
    "Automation and orchestration with VXLAN",  
    
    "Day 3 – Troubleshooting & Optimization",  
    
    "Day 3A - Troubleshooting VXLAN Networks",  
    "Common VXLAN issues and diagnostic tools",  
    "Using `show` commands, ping, and traceroute for VXLAN debugging",  
    "Debugging VXLAN tunnel issues and VTEP connectivity",  
    
    "Day 3B - Optimizing VXLAN Performance",  
    "Reducing encapsulation overhead",  
    "Load balancing and VXLAN redundancy",  
    
  ]

  export { syllabus_ccna, 
    syllabus_ccnp_encor, 
    syllabus_ccnp_enwlsi, 
    syllabus_ccnp_enarsi, 
    syllabus_ccnp_spcor,
    syllabus_ccnp_spvi,
    syllabus_ccie_sp,
    syllabus_ospf,
    syllabus_isis,
    syllabus_bgp,
    syllabus_mpls,
    syllabus_srmpls,
    syllabus_srv6,
    syllabus_vxlan,
   };
  