import React from "react";
import {
  syllabus_ccna, 
  syllabus_ccnp_enarsi, 
  syllabus_ccnp_enwlsi, 
  syllabus_ccnp_encor, 
  syllabus_ccnp_spcor,
  syllabus_ccnp_spvi,
  syllabus_ccie_sp,
  syllabus_ospf,
  syllabus_isis,
  syllabus_bgp,
  syllabus_mpls,
  syllabus_srmpls,
  syllabus_srv6,
  syllabus_vxlan,

} from "./kelas_cisco_syllabus";

import {
  Cisco_ccna_ico,
  Cisco_ccna_ico_big,
  Cisco_ccnp_encor_ico,
  Cisco_ccnp_enarsi_ico,
  Cisco_ccnp_enwlsi_ico,
  Cisco_ccnp_spcor_ico,
  Cisco_ccnp_spvi_ico,
  Cisco_ccie_sp_ico,
  Cisco_ospf_ico,
  Cisco_isis_ico,
  Cisco_bgp_ico,
  Cisco_mpls_ico,
  Cisco_srmpls_ico,
  Cisco_srv6_ico,
  Cisco_vxlan_ico,
  Cisco_ccnp_ico,
  Cucm_img,
  Mpls_img,
} from "../../components/Bpn_imgs";

interface ciscodata {
  id: number;
  img: React.JSX.Element;
  img_big: React.JSX.Element;
  title: string;
  overview: string;
  prerequisite: string;
  level: string;
  goals: string;
  lab: string;
  intended: string;
  duration: string;
  investment: string;
  comingSoon: boolean;
  syllabus: string[];
}

const cisco_data: ciscodata[] = [
  {
    id: 1,
    img: <Cisco_ccna_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "CCNA",
    duration: "5 days",
overview: "This course is intended for those wishing to qualify with ccna (cisco certified network associate). ccna certification is beginner-level certificate for people who want to work in the it network fields",
prerequisite: "Basic computer knowledge",
level: "Beginner",
goals: "Understanding the basic knowledge and configuration of cisco devices",
lab: "Yes",
intended: "Fresh graduate, noc, engineer, people who are interested in it networking field",
    investment: "2.800.000" ,
    syllabus: syllabus_ccna,
    comingSoon: false,
  },

  {
    id: 2,
    img: <Cisco_ccnp_encor_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "CCNP ENCOR",
    duration: "5 Days",
overview: "CCNP ENCOR is the core component of the CCNP Enterprise certification, equipping participants with the skills to implement and manage enterprise networks, including key technologies such as routing, switching, security, and wireless",
prerequisite: "A basic understanding of networking (CCNA level)",
level: "Intermediate",
goals: "Understand advanced routing and switching concepts",
lab: "Yes",
intended: "NOC, Network Engineer, Candidates aiming to achieve the CCNP Enterprise certification",
    investment: "4.000.000" ,
    syllabus: syllabus_ccnp_encor,
    comingSoon: false,
  },

  {
    id: 3,
    img: <Cisco_ccnp_enarsi_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "CCNP ENARSI",
    duration: "5 Days",
overview: "CCNP ENARSI (Implementing Cisco Enterprise Advanced Routing and Services) is a certification exam that validates your ability to implement and troubleshoot advanced routing technologies and services. This course covers critical areas such as Layer 3 routing, VPN technologies, and infrastructure security, preparing you for real-world enterprise network challenges",
prerequisite: "A good understanding of networking fundamentals, equivalent to the CCNA level",
level: "Intermediate",
goals: "To master the implementation and troubleshooting of advanced routing technologies in enterprise networks, including OSPF, EIGRP, BGP, MPLS, VPN infrastructure security, and network services, as preparation for the CCNP ENARSI (300-410) certification",
lab: "Yes",
intended: "Administrators, NOC, Engineer, Individuals working toward the CCNP Enterprise certification",
    investment: "4.000.000" ,
    syllabus: syllabus_ccnp_enarsi,
    comingSoon: false,
  },

  {
    id: 4,
    img: <Cisco_ccnp_enwlsi_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "CCNP ENWLSI",
    duration: "5 Days",
overview: "CCNP ENWLSI (Implementing Cisco Enterprise Wireless Networks) is a certification exam that validates your skills in implementing, securing, and troubleshooting enterprise wireless networks. The course focuses on advanced wireless technologies, including wireless design, monitoring, and policy enforcement",
prerequisite: "A strong understanding of wireless networking fundamentals, equivalent to the CCNA Wireless or CCNA level",
level: "Intermediate",
goals: "To master the implementation, management, and troubleshooting of enterprise wireless networks, including WLAN infrastructure, security, and performance optimization, as preparation for the CCNP ENWLSI certification exam (300-430)",
lab: "Yes",
intended: "Administrators, Wireless Network Engineers, Engineer, Individuals working toward the CCNP Enterprise certification",
    investment: "4.000.000" ,
    syllabus: syllabus_ccnp_enwlsi,
    comingSoon: false,
  },

  {
    id: 5,
    img: <Cisco_ccnp_spcor_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "CCNP SPCOR",
    duration: "5 Days",
    overview: "The Service Provider Core (SPCOR) course focuses on advanced concepts in service provider networks. It covers core architectures, transport technologies, virtualization, QoS, security, routing protocols, VPNs, and network automation to enable efficient service delivery and management",
    prerequisite: "Basic knowledge of networking concepts (e.g., CCNA or equivalent)",
    level: "Intermediate",
    goals: "Gain in-depth knowledge of service provider architectures and technologies",
    lab: "Yes",
    intended: "IT Professionals, NOC, Engineer, People who are interested in IT Networking field",
    investment: "4.000.000" ,
    syllabus: syllabus_ccnp_spcor,
    comingSoon: false,
  },

  {
    id: 6,
    img: <Cisco_ccnp_spvi_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "CCNP SPVI",
    duration: "4 Days",
    overview: "The Implementing Cisco Service Provider VPN Services (SPVI) training prepares you to manage end-customer Virtual Private Network (VPN) environments built over a common service provider Multiprotocol Label Switching (MPLS) backbone",
    prerequisite: "Recommended for those who are already CCNA certified",
    level: "Intermediate",
    goals: "Understand and implement various types of VPN services in service provider networks, such as L2VPN and L3VPN",
    lab: "Yes",
    intended: "Network Administrator, Network Engineer, IT Professional",
    investment: "4.000.000" ,
    syllabus: syllabus_ccnp_spvi,
    comingSoon: false,
  },

  {
    id: 7,
    img: <Cisco_ccie_sp_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "CCIE SP",
    duration: "5 Days",
overview: "The new CCIE Service Provider program prepares you for today’s expert-level job roles in service providers. Service Provider now includes automation and programmability to help you scale your service provider infrastructure",
prerequisite: "Recommended for those who already have a CCNP SP certificate",
level: "Advanced",
goals: "Demonstrate the ability to configure and optimize complex service provider infrastructures to meet performance, scalability, and security requirements",
lab: "Yes",
intended: "IT Professional, Network Engineer, Individuals aiming for the prestigious CCIE-SP certification to advance their careers in networking",
    investment: "8.100.000" ,
    syllabus: syllabus_ccie_sp,
    comingSoon: false,
  },

  {
    id: 8,
    img: <Cisco_ospf_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "FULL OSPF",
    duration: "3 Days",
overview: "OSPF is a dynamic routing protocol used for distributing routing information within an IP network. It operates based on the link-state algorithm, designed to support large-scale networks with high efficiency, fast convergence, and the ability to segment networks using areas",
prerequisite: "Basic understanding of TCP/IP networking",
level: "Intermediate",
goals: "Implement OSPF in a single-area or multi-area network",
lab: "Yes",
intended: "IT Professional, Network Engineer, Students or learners aiming to deepen their knowledge of dynamic routing",    investment: "4.000.000" ,
    syllabus: syllabus_ospf,
    comingSoon: false,
  },

  {
    id: 9,
    img: <Cisco_isis_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "FULL IS-IS",
    duration: "3 Days",
overview: "IS-IS (Intermediate System to Intermediate System) is a link-state routing protocol designed for use within an Autonomous System (AS). It is widely used in service provider networks and supports both IPv4 and IPv6. This training provides in-depth knowledge and practical skills to implement, configure, and troubleshoot IS-IS networks",
prerequisite: "Basic understanding of IP routing concepts",
level: "Intermediate",
goals: "Understand the fundamental concepts and architecture of IS-IS",
lab: "Yes",
intended: "IT Professional, Network Engineer, Service Provider Engineers, Students or learners aiming to deepen their knowledge of dynamic routing",    
investment: "4.000.000" ,
    syllabus: syllabus_isis,
    comingSoon: false,
  },

  {
    id: 10,
    img: <Cisco_bgp_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "FULL BGP",
    duration: "3 Days",
    overview: "BGP (Border Gateway Protocol) is the core routing protocol of the internet, responsible for interconnecting different Autonomous Systems (AS). This training provides a comprehensive understanding of BGP operations, configuration, and troubleshooting. It covers concepts from basic to advanced, making it suitable for enterprise and service provider network engineers",
    prerequisite: "Familiarity with basic routing protocols",
    level: "Intermediate",
    goals: "Understand the role of BGP in inter-domain routing",
    lab: "Yes",
    intended: "IT Professional, Network Engineer, Service Provider Engineers, Students or learners aiming to deepen their knowledge of dynamic routing",    
investment: "4.000.000" ,
    syllabus: syllabus_bgp,
    comingSoon: false,
  },

  {
    id: 11,
    img: <Cisco_mpls_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "FULL MPLS",
    duration: "4 Days",
overview: "MPLS (Multiprotocol Label Switching) is a flexible, high-performance routing and forwarding technology. It is widely adopted in service provider and enterprise networks for scalable traffic engineering and VPN services. This four-day training program provides participants with an in-depth understanding of MPLS concepts, configuration, advanced applications, and troubleshooting techniques",
prerequisite: "Understanding of dynamic routing protocols",
level: "Advanced",
goals: "Learn the core principles and benefits of MPLS technology",
lab: "Yes",
intended: "IT Professional, Network Engineer, Service Provider Engineers, Students or learners aiming to deepen their knowledge of dynamic routing",
investment: "8.000.000" ,
    syllabus: syllabus_mpls,
    comingSoon: false,
  },

  {
    id: 12,
    img: <Cisco_srmpls_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "FULL SR - MPLS",
    duration: "5 Days",  
    overview: "Segment Routing (SR) with MPLS is a simplified and scalable method for routing in large networks. By utilizing labels and segments, SR removes the need for traditional signaling protocols like RSVP-TE and LDP, enabling efficient traffic engineering and path optimization. This training provides a comprehensive, in-depth look at Segment Routing with MPLS and prepares engineers for deployment, optimization, and troubleshooting in modern networks",  
    prerequisite: "Familiarity with MPLS and basic MPLS operations",  
    level: "Advanced",  
    goals: "Learn how to configure SR with MPLS for traffic engineering and path optimization",  
    lab: "Yes",  
    intended: "IT Professional, Network Engineer, Service Provider Engineers, Individuals preparing for advanced network",  
investment: "8.000.000" ,
    syllabus: syllabus_srmpls,
    comingSoon: false,
  },

  {
    id: 13,
    img: <Cisco_srv6_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "FULL SRv6",
    duration: "5 Days",  
overview: "Segment Routing over IPv6 (SRv6) is a modern and efficient routing architecture designed to simplify and optimize network traffic management. SRv6 leverages the flexibility of IPv6 to enable scalable traffic engineering, simplified network operations, and enhanced automation. This 5-day training will provide a thorough understanding of SRv6, from basic concepts to advanced configurations and real-world applications",  
prerequisite: "Familiarity with segment routing (SR) concepts and traditional MPLS networks",  
level: "Advanced",  
goals: "Learn how to configure and deploy SRv6 in an enterprise or service provider network",  
lab: "Yes",  
intended: "IT Professional, Network Engineer, Service Provider Engineers, Individuals preparing for advanced network",  
investment: "8.000.000" ,
    syllabus: syllabus_srv6,
    comingSoon: false,
  },

  {
    id: 14,
    img: <Cisco_vxlan_ico/>,
    img_big: <Cisco_ccna_ico_big/>,
    title: "FULL VxLAN",
    duration: "3 Days",  
    overview: "VXLAN (Virtual Extensible LAN) is a network virtualization technology designed to extend Layer 2 networks over Layer 3 infrastructures. It encapsulates Ethernet frames in UDP packets to facilitate the creation of virtualized networks across large-scale environments. This 3-day training will cover the essential aspects of VXLAN, including its architecture, configuration, and deployment in modern data centers",  
    prerequisite: "Learn the core concepts and components of VXLAN",  
    level: "Beginner/Intermediate/Advanced",  
    goals: "Learn how to configure and deploy VXLAN in an enterprise or service provider network",  
    lab: "Yes",  
    intended: "IT Professional, Network Engineer, Data Center Professionals, Individuals seeking to understand or implement VXLAN in modern data centers",  
investment: "8.000.000" ,
    syllabus: syllabus_vxlan,
    comingSoon: false,
  },


];

export { cisco_data };