const syllabus_network: string[] = [
  "Day 1 – Fundamentals of Ethernet and Network Troubleshooting",  
"Comparing OSI Model Network Functions",  
"Deploying Ethernet Cabling",  
"Deploying Ethernet Switching",  
"Troubleshooting Ethernet Network",  
"Day 2 – IP Addressing and Network Routing",  
"Explaining IPv4 Addressing",  
"Supporting IPv4 and IPv6 Networks",  
"Configuring and Troubleshooting Routers",  
"Explaining Network Topologies and Types",  
"Day 3 – Transport Protocols and Network Services",  
"Explaining Transport Layer Protocols",  
"Explaining Network Services",  
"Explaining Network Applications",  
"Ensuring Network Availability",  
"Day 4 - Network Security and Wireless Connectivity",  
"Explaining Common Security Concepts",  
"Supporting and Troubleshooting Secure Networks",  
"Deploying and Troubleshooting Wireless Networks",  
"Comparing WAN Links and Remote Access Methods",  
"Day 5 – Advanced Security and Network Resilience",  
"Explaining Organizational and Physical Security Concepts",  
"Explaining Disaster Recovery and High Availability Concepts",  
"Applying Network Hardening Techniques",  
"Summarizing Cloud and Datacenter Architecture",  
  ];
  export { syllabus_network };
  