const syllabus_mtcre: string[] = [
  "Day 1 – Connected Route & Static Route",  
"What is Connected Route",  
"Uses of Connected Route",  
"Flag DAC",  
"Connected Route LAB",  
"When to create static routes?",  
"What is the difference between DAS and AS on IP – Route + LAB",  
"Case Study Static Route 1 + LAB",  
"Case Study Static Route 2 + LAB",  
"Recursive Next Hop + LAB",  
"Failover if there are 2 ISPs/more + LAB",  
"Loadbalance if there are 2 ISPs/more + LAB",  
"Policy Routing + Mangle + LAB",  
"Route Type + LAB",  
"Time to Live + LAB",  
"Day 2 – Dynamic Routing",  
"What is Dynamic Routing ?",  
"Static Route vs Dynamic Route + LAB",  
"IGP vs EGP",  
"Difference RIP, OSPF, BGP",  
"What is OSPF ?",  
"How to work OSPF",  
"OSPF Single Area + LAB",  
"OSPF Multi-Area + LAB",  
"OSPF Virtual Link + LAB",  
"OSPF DR-BDR + LAB",  
"OSPF Network Type (PTP, NBMA, etc) + LAB",  
"OSPF Redistribution (Type1,Type2) + LAB",  
"OSPF Cost Calculation + LAB",  
"OSPF Failover + LAB",  
"OSPF Loadbalance + LAB",  
"OSPF Routing Filter + LAB",  
"Day 3 – Virtual Private Network",  
"Differences between VPNs in MikroTik",  
"Connect Head Office – Branches with VPN",  
"EoIP + LAB",  
"PPTP + LAB",  
"L2TP + LAB",  
"SSTP + LAB",  
"PPPoE + LAB",  
"OSPF over VPN",  
"MME",  
  ];

  const syllabus_mtcwe: string[] = [
    "Day 1 – Wireless Basics and Tools",
    "Wireless Installations",
    "Wireless Routers",
    "RouterBoard Hardware",
    "Wireless Cards",
    "Antenna Types",
    "Wireless Standard 802.11 a/b/g/n",
    "Bands and Channel Width",
    "Frequencies",
    "Wireless Tools",
    "Wireless Tools + LAB (Scan, Frequency Usage, Spectral Scan/History, Snooper, Align, Sniffer)",
    "Wireless Troubleshooting",
    "Troubleshooting Wireless Client + LAB (Registration Table Analysis, AckTimeout/Distance, TX/RX Signal Strength, Frames and HW-frames, Data Rates)",
    "Day 2 – Advanced Wireless Settings and Security",
    "Wireless Advanced Settings",
    "Advanced Wireless Tab Settings + LAB (HW-retries, HW-protection, Adaptive-noise-immunity, WMM, Country Regulation Settings, TX-power + LAB, VirtualAP)",
    "802.11n Wireless Protocol + LAB (Features, Data Rates, Channel Bonding, Frame Aggregation, TX-power for N Cards, Chain Settings)",
    "Wireless Link Debugging",
    "Wireless Security",
    "Wireless Security Measures + LAB (Access Management, Access-List/Connect-List, RADIUS, Authentication, Encryption, EAP, Management Frame Protection)",
    "Day 3 – Protocols and Bridging",
    "WDS and MESH",
    "Wireless WDS Protocol + LAB (Dynamic/Static WDS, RSTP Bridge)",
    "Wireless MESH + LAB (HWMP+ Mesh)",
    "Wireless Bridging",
    "Wireless Transparent Bridge + LAB (WDS Bridging, AP/Station-WDS, Pseudobridge, MPLS/VPLS Tunnel)",
    "Nstreme Protocol",
    "MikroTik Wireless Nstreme Protocol + LAB (Features, Configuration Options, Nstreme Dual, Troubleshooting)",
    "Nv2 Protocol MikroTik Wireless Nv2 Protocol + LAB",
 ];
 const syllabus_mtctce: string[] = [
  "Day 1 – Packet Flow, Routing, and Firewall",
"Overview of packet flow and its necessity in network management",
"Simple examples of how packets travel through the network (routing, bridging, and connection to routers)",
"LAB: Packet flow demonstration with routing and bridging scenarios",
"Firewall configuration: Filters, NAT, and mangle rules",
"LAB: Setting up filters, NAT, and mangle for network traffic management",
"Advanced firewall rules using the 'advanced' and 'extra' tabs for complex conditions",
"Day 2 – QoS, DNS, and DHCP",
"Introduction to Quality of Service (QoS) using HTB for bandwidth management",
"LAB: Configuring HTB, burst, and queue types for traffic control",
"Managing simple queues and queue tree interaction for advanced QoS",
"DNS configuration: Client settings, static entries, and cache management",
"LAB: Configuring DNS client and static DNS entries",
"DHCP client, server, and relay configuration",
"LAB: Setting up DHCP client, server, and relay, and analyzing DHCP communication",
"Day 3 – Web Proxy and Advanced Networking Features",
"Web Proxy basics: Configuration and rule management",
"LAB: Setting up proxy rules and using regular expressions for filtering",
"Advanced DHCP configuration: Optimizing client identification, server settings, and relay setup",
"LAB: Combining all concepts with advanced configurations for network traffic management and security",
];

const syllabus_mtcume: string[] = [
  "Day 1 – Fundamentals and PPP",
  "Overview of PPP and its applications",
  "PPP configuration, including profiles and secrets",
  "IP Pool configuration for address management",
  "PPTP and L2TP theory and configuration (Client and Server)",
  "Hands-on Lab: Configuring PPP, PPTP, and L2TP",
  "Day 2 – Advanced PPP and Bridging",
  "PPPoE theory and configuration (Client and Server)",
  "Security and encryption for PPPoE",
  "Interface ECMP configuration",
  "Bridging concepts and configuration with L2TP, EoIP, and VPLS",
  "Hands-on Lab: Setting up PPPoE and Bridging",
  "Day 3 – Security, HotSpot, and RADIUS",
  "IPSec theory and implementation",
  "HotSpot configuration and user management",
  "RADIUS client and server setup, including User Manager",
  "Hands-on Lab: Implementing IPSec, HotSpot",  
];

const syllabus_mtcipv6: string[] = [
  "Day 1 – Fundamentals of IPv6",
"Introduction to IPv6",
"Overview of IPv6 Protocol",
"Structure and components of IPv6 packets",
"Key differences between IPv4 and IPv6",
"Hands-on Lab: Configuring basic IPv6 on MikroTik routers",
"Day 2 – Advanced IPv6 Concepts",
"IPv6 Security",
"Common threats and mitigation techniques in IPv6 networks",
"Transition Mechanisms:",
"Dual Stack, Tunneling, and NAT64",
"Hands-on Lab: Implementing transition mechanisms in MikroTik",
"Day 3 – IPv6 Network Implementation and Interoperability",
"IPv6 Interoperability with IPv4 networks",
"Routing and addressing best practices",
"Hands-on Lab: Setting up a fully operational IPv6 network",
"Final review, troubleshooting, and Q&A sessions",
];
const syllabus_mtcine: string[] = [
  "Day 1 – Fundamentals of IPv6",
"Introduction to IPv6",
"Overview of IPv6 Protocol",
"Structure and components of IPv6 packets",
"Key differences between IPv4 and IPv6",
"Hands-on Lab: Configuring basic IPv6 on MikroTik routers",
"Day 2 – Advanced IPv6 Concepts",
"IPv6 Security",
"Common threats and mitigation techniques in IPv6 networks",
"Transition Mechanisms:",
"Dual Stack, Tunneling, and NAT64",
"Hands-on Lab: Implementing transition mechanisms in MikroTik",
"Day 3 – IPv6 Network Implementation and Interoperability",
"IPv6 Interoperability with IPv4 networks",
"Routing and addressing best practices",
"Hands-on Lab: Setting up a fully operational IPv6 network",
"Final review, troubleshooting, and Q&A sessions",
];

const syllabus_mtcna: string[] = [
  "Day 1 – Introduction to MikroTik and Basic Configuration",  
  "Overview of MikroTik products and RouterOS",  
  "Initial setup and accessing the MikroTik device",  
  "Basic networking concepts: IP addresses, subnets, and gateways",  
  "Firewall basics",  
  
  "Day 2 – Advanced Firewall and QoS",  
  "RouterOS connection tracking",  
  "Basic address list + LAB",  
  "Source NAT",  
  "Destination NAT",  
  "Simple Queue + LAB",  
  "Bandwidth test + LAB",  
  "Interface traffic monitor",  
  "PCQ Queueing",  
  
  "Day 3 – Network Management, Wireless, and Tunnels",  
  "ARP modes",  
  "RouterOS ARP table",  
  "DHCP server and client + LAB",  
  "Wireless configuration",  
  "Setup simple wireless link + LAB",  
  "MAC address filtering + LAB",  
  "MikroTik wireless protocols + LAB",  
  "Routing basics",  
  "Routing overview",  
  "Static routing",  
  "Tunnels",  
  "Tunnel overview (PPPoE, PPTP, L2TP, EoIP)",  
  
];

  export { syllabus_mtcre,syllabus_mtcwe,syllabus_mtctce,syllabus_mtcume,syllabus_mtcine, syllabus_mtcipv6, syllabus_mtcna };
  