const syllabus_jnciajunos: string[] = [
 "Day 1 – Introduction Networking and Junos Fundamentals",  
"Core networking concepts: Subnetting, ARP, and routing fundamentals",  
"Introduction to Junos OS architecture and CLI basics",  
"Initial device setup and user interface options (CLI and J-Web)",  
"Basic device configuration and verification",  
"Day 2 – Routing Protocols and Layer 2 Switching",  
"Static routing and introduction to dynamic protocols (OSPF, BGP overview)",  
"Layer 2 concepts: VLANs, STP, and trunking",  
"Configuring and verifying VLANs and inter-VLAN routing",  
"Setting up routing and Layer 2 switching",  
"Day 3 – Security and Policies",  
"Firewall filters and security zones in Junos OS",  
"Configuring and managing NAT",  
"Overview of Juniper’s security concepts",  
"Hands-on Lab: Implementing security policies and NAT",  
"Day 4 – Network Management and Operations",  
"Monitoring and logging with Junos OS",  
"Using operational commands for troubleshooting",  
"Backup, restore, and upgrading Junos OS",  
"Network diagnostics and Junos OS upgrades",  
  ];

  const syllabus_jncissp: string[] = [
    "Day 1 – Protocol-Independent Routing & OSPF",  
"Introduction to Protocol-Independent Routing",  
"Static, aggregate, and generated routes",  
"Martian addresses",  
"Routing instances and RIB groups",  
"Load balancing",  
"Filter-based forwarding",  
"Configuration, Monitoring, and Troubleshooting",  
"Static, aggregate, and generated routes",  
"Load balancing",  
"Filter-based forwarding",  
"Introduction to OSPF",  
"Link-state database",  
"OSPF packet types",  
"Router ID",  
"Adjacencies and neighbors",  
"DR and BDR",  
"OSPF areas and router types",  
"Link-state advertisement (LSA) packet types",  
"Configuration, Monitoring, and Troubleshooting OSPF",  
"Areas, interfaces, and neighbors",  
"Routing policy application",  
"Troubleshooting tools",  
"Day 2 – IS-IS & BGP",  
"Introduction to IS-IS",  
"Link-state database",  
"IS-IS PDUs and TLVs",  
"Adjacencies and neighbors",  
"Levels and areas",  
"Designated Intermediate System (DIS)",  
"Metrics",  
"Configuration, Monitoring, and Troubleshooting IS-IS",  
"Levels, interfaces, and adjacencies",  
"Routing policy application",  
"Introduction to BGP",  
"BGP basic operation",  
"BGP message types",  
"Attributes and path selection process",  
"IBGP and EBGP functionality and interaction",  
"Configuration, Monitoring, and Troubleshooting BGP",  
"Groups and peers",  
"Routing policy application",  
"Day 3 – Layer 2 Bridging, VLANs, and STP",  
"Introduction to Layer 2 Bridging",  
"Service provider switching platforms",  
"Bridging elements and frame processing",  
"Virtual switches and Q-in-Q tunneling",  
"VLAN Concepts",  
"Port modes, tagging, and IRB",  
"Configuration, Monitoring, and Troubleshooting Bridging and VLANs",  
"Interfaces, ports, VLANs, IRB, and Q-in-Q",  
"Introduction to STP and Variants",  
"STP, RSTP, MSTP, and VSTP concepts",  
"Port roles and states",  
"BPDU and spanning-tree security",  
"Configuration, Monitoring, and Troubleshooting STP",  
"Day 4 – MPLS, IPv6, and Tunneling",  
"Introduction to MPLS",  
"MPLS terminology and packet header",  
"End-to-end packet flow and labels",  
"RSVP, LDP, and segment routing",  
"Configuration, Monitoring, and Troubleshooting MPLS",  
"MPLS forwarding and LSPs",  
"Introduction to IPv6",  
"IPv4 vs IPv6",  
"Address types, scopes, and autoconfiguration",  
"Tunneling concepts",  
"Configuration, Monitoring, and Troubleshooting IPv6",  
"Interfaces, static routes, dynamic routing (OSPFv3, IS-IS, BGP)",  
"IPv6 over IPv4 tunneling",  
"Day 5 – High Availability",  
"Introduction to High Availability",  
"LAG and MC-LAG",  
"Graceful restart (GR) and GRES",  
"Nonstop bridging (NSB) and nonstop active routing (NSR)",  
"BFD and VRRP",  
"Unified ISSU",  
"Configuration, Monitoring, and Troubleshooting High Availability",  
"Comprehensive Lab Practice",  
"Protocol-independent routing (static, aggregate routes)",  
"OSPF, IS-IS, BGP configuration",  
"VLANs, MPLS, and IPv6",  
"High Availability and troubleshooting scenarios",  
 ];
 const syllabus_jncisent: string[] = [
  "Day 1 – Layer 2 Switching and VLANs",  
"Understand Layer 2 switching concepts and frame processing",  
"Learn about VLANs, ports, tagging, and native VLANs",  
"Configure and troubleshoot VLANs, interfaces, and inter-VLAN routing",  
"Set up Spanning Tree Protocol (STP) and Rapid Spanning Tree Protocol (RSTP)",  
"Purpose of virtual links",  
"Day 2 – Spanning Tree and Layer 2 Security",  
"Study Spanning Tree Protocol (STP) and Rapid Spanning Tree Protocol (RSTP)",  
"Learn about BPDU, loop, and root protection",  
"Implement port security features like MAC limiting, DHCP snooping, DAI, and storm control",  
"Configure and troubleshoot STP, RSTP, and Layer 2 security features",  
"Apply firewall filter configurations",  
"Day 3 – Protocol Independent Routing and OSPF",  
"Configure static, aggregate, and generated routes",  
"Learn about routing instances, RIB groups, and filter-based forwarding",  
"Understand OSPF, link-state database, router IDs, and OSPF packet types",  
"Configure OSPF areas, interfaces, and neighbors",  
"Apply routing policies and troubleshoot OSPF",  
"Day 4 – IS-IS and BGP",  
"Learn about IS-IS, link-state database, and Protocol Data Units (PDUs)",  
"Configure and troubleshoot IS-IS levels, interfaces, and adjacencies",  
"Study BGP operation, message types, and attributes",  
"Learn how to configure BGP groups, peers, and routing policies",  
"Troubleshoot BGP with tools like ping, traceroute, and show commands",  
"Day 5 – Tunnels and High Availability",  
"Understand IP tunneling concepts like GRE and IP-IP tunneling",  
"Configure and troubleshoot GRE and IP-IP tunnels",  
"Learn about high availability concepts such as link aggregation and virtual chassis",  
"Configure and monitor VRRP, Graceful Restart, and Nonstop Active Routing (NSR)",  
"Troubleshoot high availability features using traceoptions, show commands, and logging",  
];

  export { syllabus_jnciajunos,syllabus_jncissp,syllabus_jncisent };
  