const syllabus_fcf: string[] = [
   "Day 1 – Introduction to Cyber Security and FortiGate Firewalls",  
"Introduction to cybersecurity and common cyber threats",  
"Basic security concepts and risk management",  
"Fortinet’s portfolio and security solutions",  
"FortiGate firewall overview and architecture",  
"Basic configuration and management of FortiGate firewalls",  
"Configuring interfaces, IP addressing, and basic routing",  

"Day 2 – Firewall Policies, VPNs, and Secure Connectivity",  
"FortiGate Firewall Policies",  
"Creating and managing security policies",  
"Traffic filtering and security profiles (IPS, Antivirus, Web Filtering)",  
"Virtual Private Networks (VPNs)",  
"VPN concepts: IPsec VPN and SSL VPN",  
"Configuring Site-to-Site and Remote Access VPNs",  
"Configuring an IPsec VPN tunnel and Remote Access VPN",  

"Day 3 – Threat Protection, Monitoring, and Troubleshooting",  
"FortiGate Threat Protection",  
"Intrusion Prevention System (IPS), Web Filtering, and Application Control",  
"Configuring Antivirus and Antispam services",  
"Logging and Monitoring",  
"Introduction to FortiAnalyzer for logging and monitoring",  
"Basic troubleshooting techniques and best practices",  
"Hands-On: Threat Protection and Monitoring",  
"Configuring IPS, Web Filtering, and monitoring logs",  
  ];

  const syllabus_fca: string[] = [
"Day 1 – Introduction to Cyber Security and Fortinet",  
"Overview of Cybersecurity Trends and Threats",  
"Introduction to Fortinet Products and Services",  
"FortiGate Initial Setup and Configuration",  
"Understanding Firewall Policies and NAT",  
"Hands-on Lab: Configuring Basic Firewall Rules",  

"Day 2 – FortiGate Configuration and Management",  
"FortiGate configuration (firewall, VPN, IPS)",  
"User, group, and role management",  
"VPN configuration (IPSec, SSL/TLS)",  
"Intrusion Prevention System (IPS) configuration",  
"Log and reporting configuration",  

"Day 3 – Advanced Security and Certification Exam",  
"Advanced security features (Web Application Firewall, Email Security)",  
"Log analysis and reporting",  
"FCA certification exam",  
"Discussion of real-world security scenarios",  
"Action plan for improving network security",   
   ];

   const syllabus_nse4: string[] = [
    "Day 1 – Introduction and Initial Configuration, Firewall Policies, and NAT",  
"Overview of FortiGate devices and features",  
"Initial device setup and configuration",  
"Basic network settings (IP addresses, interfaces, DNS)",  
"FortiGate web-based interface (GUI) and CLI introduction",  
"Basic system configuration and management",  

"Firewall Policies",  
"Overview of firewall policies and their function",  
"Configuring basic and advanced firewall policies",  
"Security policies (source, destination, services, etc.)",  
"Policy testing and troubleshooting",  
"Policy optimization for performance",  

"Network Address Translation (NAT)",  
"Introduction to NAT and its types (source NAT, destination NAT)",  
"Configuring NAT on FortiGate",  
"Troubleshooting NAT-related issues",  
"Understanding the impact of NAT on traffic flow",  

"Day 2 – Firewall Authentication, Logging, Monitoring, and Certificate Operations",  

"Firewall Authentication",  
"Configuring authentication methods (local, RADIUS, LDAP)",  
"Using FortiGate for user authentication and authorization",  
"Single Sign-On (SSO) integration",  
"User group management and policy enforcement",  

"Logging and Monitoring",  
"Configuring logging settings on FortiGate",  
"Log management and analysis",  
"Using FortiView for real-time monitoring",  
"Report generation and log retention",  

"Certificate Operations",  
"Introduction to SSL/TLS and certificates",  
"Installing and configuring SSL certificates on FortiGate",  
"Using certificates for SSL VPNs, SSL inspection, and web filtering",  
"Certificate authority (CA) management",  

"Day 3 – Web Filtering, Application Control, Antivirus, IPS/DoS, and Security Fabric",  

"Configuring web filtering profiles",  
"URL filtering and category-based filtering",  
"Web traffic inspection and reporting",  
"Web filtering for both HTTP and HTTPS traffic",  

"Application Control",  
"Introduction to application control and its importance",  
"Configuring application control profiles",  
"Blocking and monitoring application traffic",  
"Analyzing application control logs and reports",  

"Antivirus",  
"Configuring antivirus profiles on FortiGate",  
"Antivirus scanning of traffic (HTTP, SMTP, FTP, etc.)",  
"Using antivirus in combination with other security profiles",  
"Troubleshooting antivirus-related issues",  

"Intrusion Prevention System (IPS) and Denial of Service (DoS)",  
"Overview of IPS and DoS protection mechanisms",  
"Configuring IPS profiles to detect and block attacks",  
"Configuring DoS prevention policies",  
"Analyzing IPS and DoS logs",  

"Security Fabric",  
"Overview of Fortinet Security Fabric and its architecture",  
"Integrating FortiGate devices with Security Fabric",  
"Security Fabric features and benefits",  
"Configuring and managing Security Fabric components (FortiAnalyzer, FortiManager, FortiSwitch, etc.)",    
       ];
  
       const syllabus_nse7: string[] = [
        
        "Day 1 – Initial Configuration and SD-WAN Local Breakout",  
"Configure Internet and MPLS Cloud",  
"Configure FortiGate HQ and Branch",  
"Configure Docker HQ and Branch",  
"Configure Web Server and R-Client",  
"Verification of Configuration",  
"SD-WAN Local Breakout Configuration for HQ and Branch",  
"SD-WAN Member Configuration",  
"Static Route Configuration",  
"DNS Server Configuration",  
"Firewall Policy Configuration",  
"Verifying Local Breakout on Web-Server and R-Client",  

"Day 2 – Performance SLA, SD-WAN Rules, and Traffic Shaping",  
"Performance SLA Configuration for HQ and Branch",  
"Configure Performance SLA",  
"Verifying Performance SLA",  
"SD-WAN Rules Configuration for HQ and Branch",  
"SD-WAN Rules Scenario 1 and Scenario 2",  
"Static Route and Firewall Policy for SD-WAN Rules",  
"Verifying SD-WAN Rules",  
"Traffic Shaping Configuration for Branch",  
"Configure Traffic Shapers",  
"Configure Traffic Shaping Policy",  
"Verifying Traffic Shaping on Docker-Client",  

"Day 3 – IPSec VPN, FortiManager Integration, and ADVPN",  
"IPSec VPN Configuration for HQ and Branch",  
"Dialup IPSec Configuration",  
"SD-WAN Member Configuration for IPSec VPN",  
"SD-WAN Rules, Firewall Policy, and Static Route for IPSec",  
"Verifying IPSec VPN",  
"Integration to FortiManager",  
"Initial Configuration of FortiManager",  
"Adding FW-HQ and FW-Branch to FMG",  
"Configuring Meta Fields, Variables, and CLI Scripts",  
"Applying CLI Template to FW-Branch",  
"Verifying Configuration",  
"ADVPN Configuration for Hub and Spokes",  
"Initial Configuration of Hub and Spokes",  
"Configure ADVPN, BGP Routing, and Firewall Policy",  
"Verifying ADVPN Connectivity on Hub and Spokes",  
       ];

  export { 
    syllabus_fcf, 
    syllabus_fca,
    syllabus_nse4,
    syllabus_nse7,
   };
  