const syllabus_hciadatacom: string[] = [
  "Day 1 – Data Communication and Network Basics",  
"Basic Concepts of Data Communication",  
"Network Reference Model",  
"Huawei VRP Basics",  
"IPv6 Basics",  
"WLAN Basics",  
"Day 2 – Constructing an Ethernet Switching Network",  
"Ethernet Switching Basics",  
"VLAN Principles and Configuration",  
"Spanning Tree Protocol",  
"Ethernet Link Aggregation and Switch Stacking",  
"Implements Communication Between VLANs",  
"Day 3 – Constructing an Interconnected IP Network DHCP principles",  
"Network Layer Protocol and IP Addressing",  
"IP Routing Basics",  
"OSPF Basics",  
"Day 4 – Network Security and Network Access Basic",  
"ACL Principles and Configuration",  
"AAA Principles and Configuration",  
"NAT Basics",  
"Day 5 – WAN Technology Basics",  
"Basic WAN Concepts",  
"Common WAN Technologies",  
"Working Principles of PPP and PPPoE",  
"Configuring PPP and PPPoE",  
"Basic Concepts of MPLS/SR",  
  ];
  
  export { syllabus_hciadatacom };
  